# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present EmuELEC

PKG_NAME="tsugaru-lr"
PKG_VERSION="41a9ea265f197a7e2593b5eb04c17cdb7446f95b"
PKG_SHA256="e166282c350a54caace35d94e649ec4352ec554860aee9fac970a8af82e34ec4"
PKG_LICENSE="BSD-3-Clause"
PKG_SITE="https://github.com/mixerjdp/fmtowns-master"
PKG_URL="${PKG_SITE}/archive/${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain mame"
PKG_LONGDESC="FM Towns / Tsugaru libretro core"
PKG_TOOLCHAIN="make"

pre_configure_target() {
  # eigccarm.h stub (missing from repo)
  cat > "${PKG_BUILD}/src/osd/eigccarm.h" << 'EOF'
#ifndef MAME_OSD_EIGCCARM_H
#define MAME_OSD_EIGCCARM_H
#if defined(__aarch64__)
#define recip_approx _recip_approx
static inline float __attribute__((const,always_inline)) _recip_approx(float v) {
  float r; __asm__(" frecpe %s[r], %s[v]\n" : [r]"=w"(r) : [v]"w"(v)); return r; }
#endif
#endif
EOF

  # drivlist.cpp (normally generated by makelist)
  mkdir -p "${PKG_BUILD}/build/generated/mame/fmtowns"
  cat > "${PKG_BUILD}/build/generated/mame/fmtowns/drivlist.cpp" << 'EOF'
#include "emu.h"
#include "drivenum.h"
GAME_EXTERN(___empty); GAME_EXTERN(carmarty); GAME_EXTERN(fmtmarty);
GAME_EXTERN(fmtmarty2); GAME_EXTERN(fmtowns); GAME_EXTERN(fmtownsftv);
GAME_EXTERN(fmtownshr); GAME_EXTERN(fmtownsmx); GAME_EXTERN(fmtownssj);
GAME_EXTERN(fmtownsux); GAME_EXTERN(fmtownsv03);
const game_driver * const driver_list::s_drivers_sorted[] = {
  &GAME_NAME(___empty), &GAME_NAME(carmarty), &GAME_NAME(fmtmarty),
  &GAME_NAME(fmtmarty2), &GAME_NAME(fmtowns), &GAME_NAME(fmtownsftv),
  &GAME_NAME(fmtownshr), &GAME_NAME(fmtownsmx), &GAME_NAME(fmtownssj),
  &GAME_NAME(fmtownsux), &GAME_NAME(fmtownsv03),
};
const std::size_t driver_list::s_driver_count = std::size(s_drivers_sorted);
EOF

  # retro_globals_stub (globals from libretro.cpp not present in libosd_retro.a)
  cat > "${PKG_BUILD}/libretro/retro_globals_stub.cpp" << 'EOF'
#include <cstdint>
#include <cstddef>
typedef void(*retro_log_printf_t)(int,const char*,...);
typedef bool(*retro_environment_t)(unsigned,void*);
typedef void(*retro_video_refresh_t)(const void*,unsigned,unsigned,size_t);
typedef size_t(*retro_audio_sample_batch_t)(const int16_t*,size_t);
typedef void(*retro_input_poll_t)(void);
typedef int16_t(*retro_input_state_t)(unsigned,unsigned,unsigned,unsigned);
int RLOOP=1,retro_pause=0,SHIFTON=-1,fb_width=640,fb_height=480;
int max_width=720,max_height=720,video_changed=0,screen_configured=0;
int CDD_status=0,POSTNOTIFY=0,ENDEXEC=0;
char RPATH[512]={};
bool first_run=true,audio_ready=false,retro_load_ok=false;
bool libretro_supports_bitmasks=false,libretro_supports_ff_override=false,libretro_ff_enabled=false;
float retro_aspect=4.0f/3.0f,view_aspect=1.0f,sample_rate=48000.0f,retro_fps=60.0f;
const char *retro_save_directory=nullptr,*retro_system_directory=nullptr,*retro_content_directory=nullptr;
unsigned int videoBuffer[4096*3072];
retro_log_printf_t log_cb=nullptr; retro_environment_t environ_cb=nullptr;
retro_input_state_t input_state_cb=nullptr; retro_input_poll_t input_poll_cb=nullptr;
retro_video_refresh_t video_cb=nullptr; retro_audio_sample_batch_t audio_batch_cb=nullptr;
EOF
}

make_target() {
  local MB="${PKG_BUILD%/build/*}/build/mame-2ffec28bcf65eceb395722c9d721e7d4523fbb56"
  local LR="${MB}/build/libretro/bin"
  local OD="${PKG_BUILD}/libretro"
  local FL="-O3 -DNDEBUG -std=c++20 -fPIC"
  local INC="-I${PKG_BUILD}/src/emu -I${PKG_BUILD}/src/devices -I${PKG_BUILD}/src/osd
    -I${PKG_BUILD}/src/lib -I${PKG_BUILD}/src/lib/util -I${PKG_BUILD}/src/mame
    -I${PKG_BUILD}/src/frontend/mame -I${PKG_BUILD}/3rdparty
    -I${PKG_BUILD}/3rdparty/rapidjson/include -I${PKG_BUILD}/3rdparty/zlib
    -I${PKG_BUILD}/3rdparty/flac/include -I${PKG_BUILD}/3rdparty/asio/include
    -I${PKG_BUILD}/build/generated/emu -I${PKG_BUILD}/build/generated/emu/layout
    -I${PKG_BUILD}/build/generated/mame/layout
    -I${MB}/src/osd/libretro -I${MB}/src/osd/libretro/libretro-internal"

  ${CXX} ${FL} -c ${OD}/retro_globals_stub.cpp -o ${OD}/retro_globals_stub.o
  ${CXX} ${FL} -I${MB}/src/osd -I${MB}/src/osd/modules/netdev \
    -c ${MB}/src/osd/modules/netdev/netdev_common.cpp -o ${OD}/netdev_common.o
  for src in machine video sound; do
    ${CXX} ${FL} -D__LIBRETRO__ -DLIBRETRO_OS=unix ${INC} \
      -c ${PKG_BUILD}/src/emu/${src}.cpp -o ${OD}/tsugaru_${src}.o
  done

  make -f libretro/Makefile.libretro \
    SRCROOT="${PKG_BUILD}" OBJDIR="${OD}" TARGET_OS=linux \
    CXX="${CXX}" STRIP="${STRIP}" ARCH="${ARCH}" \
    SHARED_FLAGS="-shared" EXTRA_LIBS="" \
    LDFLAGS="${OD}/retro_globals_stub.o ${OD}/netdev_common.o \
      ${OD}/tsugaru_machine.o ${OD}/tsugaru_video.o ${OD}/tsugaru_sound.o \
      -Wl,--start-group \
      ${LR}/mame_mame/liboptional.a ${LR}/libemu.a \
      ${LR}/mame_mame/libformats.a ${LR}/mame_mame/libdasm.a \
      ${LR}/mame_mame/libfujitsu.a ${LR}/libutils.a \
      ${LR}/libsoftfloat.a ${LR}/libsoftfloat3.a ${LR}/libwdlfft.a \
      ${LR}/libymfm.a ${LR}/libjpeg.a ${LR}/lib7z.a \
      ${LR}/liblua.a ${LR}/liblualibs.a ${LR}/liblinenoise.a \
      ${LR}/libzstd.a ${LR}/libnetlist.a ${LR}/libasmjit.a \
      ${LR}/libutf8proc.a ${LR}/mame_mame/libshared.a \
      ${LR}/mame_mame/libocore_retro.a ${LR}/mame_mame/libosd_retro.a \
      -Wl,--end-group"
}

makeinstall_target() {
  mkdir -p ${INSTALL}/usr/lib/libretro
  cp -f ${PKG_BUILD}/libretro/fmtowns_libretro.so ${INSTALL}/usr/lib/libretro/
}