# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present EmuELEC

PKG_NAME="tsugaru-lr"
PKG_VERSION="41a9ea265f197a7e2593b5eb04c17cdb7446f95b"
PKG_SHA256="e166282c350a54caace35d94e649ec4352ec554860aee9fac970a8af82e34ec4"
PKG_LICENSE="BSD-3-Clause"
PKG_SITE="https://github.com/mixerjdp/fmtowns-master"
PKG_URL="${PKG_SITE}/archive/${PKG_VERSION}.tar.gz"

PKG_DEPENDS_TARGET="toolchain mame"
PKG_LONGDESC="FM Towns / Tsugaru libretro core"
PKG_TOOLCHAIN="make"

pre_configure_target() {
  # eigccarm.h is absent from this repo; eminline.h includes it on aarch64.
  cat > "${PKG_BUILD}/src/osd/eigccarm.h" << 'EOF'
// license:BSD-3-Clause
// Minimal eigccarm.h stub for EmuELEC aarch64 cross-compile.
#ifndef MAME_OSD_EIGCCARM_H
#define MAME_OSD_EIGCCARM_H
#if defined(__aarch64__)
#define recip_approx _recip_approx
static inline float __attribute__((const, always_inline))
_recip_approx(float value)
{
	float result;
	__asm__(" frecpe  %s[result], %s[value] \n"
		: [result] "=w" (result)
		: [value]  "w"  (value));
	return result;
}
#endif
#endif // MAME_OSD_EIGCCARM_H
EOF

  # drivlist.cpp is normally generated by MAME's host-side makelist tool.
  mkdir -p "${PKG_BUILD}/build/generated/mame/fmtowns"
  cat > "${PKG_BUILD}/build/generated/mame/fmtowns/drivlist.cpp" << 'EOF'
// license:BSD-3-Clause
// Hand-written drivlist.cpp for EmuELEC aarch64 cross-compile.
#include "emu.h"
#include "drivenum.h"

GAME_EXTERN(___empty);
GAME_EXTERN(carmarty);
GAME_EXTERN(fmtmarty);
GAME_EXTERN(fmtmarty2);
GAME_EXTERN(fmtowns);
GAME_EXTERN(fmtownsftv);
GAME_EXTERN(fmtownshr);
GAME_EXTERN(fmtownsmx);
GAME_EXTERN(fmtownssj);
GAME_EXTERN(fmtownsux);
GAME_EXTERN(fmtownsv03);

const game_driver * const driver_list::s_drivers_sorted[] =
{
	&GAME_NAME(___empty),
	&GAME_NAME(carmarty),
	&GAME_NAME(fmtmarty),
	&GAME_NAME(fmtmarty2),
	&GAME_NAME(fmtowns),
	&GAME_NAME(fmtownsftv),
	&GAME_NAME(fmtownshr),
	&GAME_NAME(fmtownsmx),
	&GAME_NAME(fmtownssj),
	&GAME_NAME(fmtownsux),
	&GAME_NAME(fmtownsv03),
};

const std::size_t driver_list::s_driver_count = std::size(s_drivers_sorted);
EOF

  # retro_globals_stub.cpp: all globals from MAME's libretro.cpp + retro_init.cpp
  # referenced by libocore_retro.a / libosd_retro.a via libretro_shared.h externs.
  # We cannot link libretro.cpp wholesale — it conflicts with Tsugaru's retro_* API.
  cat > "${PKG_BUILD}/libretro/retro_globals_stub.cpp" << 'EOF'
// Globals from MAME's libretro.cpp that are NOT in libosd_retro.a.
// retro_init.cpp globals are already compiled into libosd_retro.a(retro_init.o)
// and pulled in automatically. libretro.o is NOT pulled in (no direct reference
// from the 4 wrapper .o files), so we define its globals here manually.
// retro_* API functions are provided by fmtowns_libretro.cpp instead.
#include <cstdint>
#include <cstddef>

typedef void    (*retro_log_printf_t)(int, const char *, ...);
typedef bool    (*retro_environment_t)(unsigned, void *);
typedef void    (*retro_video_refresh_t)(const void *, unsigned, unsigned, size_t);
typedef size_t  (*retro_audio_sample_batch_t)(const int16_t *, size_t);
typedef void    (*retro_input_poll_t)(void);
typedef int16_t (*retro_input_state_t)(unsigned, unsigned, unsigned, unsigned);

// From libretro.cpp only
int   RLOOP           = 1;
int   retro_pause     = 0;
int   SHIFTON         = -1;
char  RPATH[512]      = {};
bool  first_run       = true;
bool  audio_ready     = false;
bool  retro_load_ok   = false;
bool  libretro_supports_bitmasks    = false;
bool  libretro_supports_ff_override = false;
bool  libretro_ff_enabled           = false;
int   fb_width        = 640;
int   fb_height       = 480;
int   max_width       = 720;
int   max_height      = 720;
float retro_aspect    = 4.0f / 3.0f;
float view_aspect     = 1.0f;
float sample_rate     = 48000.0f;
float retro_fps       = 60.0f;
int   video_changed   = 0;
int   screen_configured = 0;
int   CDD_status      = 0;

const char *retro_save_directory    = nullptr;
const char *retro_system_directory  = nullptr;
const char *retro_content_directory = nullptr;

unsigned int videoBuffer[4096 * 3072];

retro_log_printf_t         log_cb         = nullptr;
retro_environment_t        environ_cb     = nullptr;
retro_input_state_t        input_state_cb = nullptr;
retro_input_poll_t         input_poll_cb  = nullptr;
retro_video_refresh_t      video_cb       = nullptr;
retro_audio_sample_batch_t audio_batch_cb = nullptr;

// Referenced by MAME 0.287 machine.cpp but not defined in the retro OSD layer.
int POSTNOTIFY = 0;
int ENDEXEC    = 0;


EOF
}

make_target() {
  local MAME_BUILD="${PKG_BUILD%/build/*}/build/mame-2ffec28bcf65eceb395722c9d721e7d4523fbb56"
  local LIBROOT="${MAME_BUILD}/build/libretro/bin"

  # Compile retro globals stub (replaces libretro.cpp globals without its conflicting functions)
  ${CXX} -O3 -DNDEBUG -std=c++20 -fPIC \
    -c ${PKG_BUILD}/libretro/retro_globals_stub.cpp \
    -o ${PKG_BUILD}/libretro/retro_globals_stub.o

  # netdev_common.cpp excluded from retro OSD build but referenced by libemu.a
  ${CXX} -O3 -DNDEBUG -std=c++20 -fPIC \
    -I${MAME_BUILD}/src/osd \
    -I${MAME_BUILD}/src/osd/modules/netdev \
    -c ${MAME_BUILD}/src/osd/modules/netdev/netdev_common.cpp \
    -o ${PKG_BUILD}/libretro/netdev_common.o

  # Tsugaru modifies machine.cpp, video.cpp and sound.cpp with #ifdef __LIBRETRO__
  # guards adding libretro_start/libretro_run_slice/libretro_stop and other hooks.
  # These symbols are missing from MAME 0.287's libemu.a. Compile them from
  # Tsugaru's src/emu/ with -D__LIBRETRO__ so they override libemu.a at link time.
  local EMU_INCLUDES="\
    -I${PKG_BUILD}/src/emu \
    -I${PKG_BUILD}/src/devices \
    -I${PKG_BUILD}/src/osd \
    -I${PKG_BUILD}/src/lib \
    -I${PKG_BUILD}/src/lib/util \
    -I${PKG_BUILD}/src/mame \
    -I${PKG_BUILD}/src/frontend/mame \
    -I${PKG_BUILD}/3rdparty \
    -I${PKG_BUILD}/3rdparty/rapidjson/include \
    -I${PKG_BUILD}/3rdparty/zlib \
    -I${PKG_BUILD}/3rdparty/flac/include \
    -I${PKG_BUILD}/3rdparty/asio/include \
    -I${PKG_BUILD}/build/generated/emu \
    -I${PKG_BUILD}/build/generated/emu/layout \
    -I${PKG_BUILD}/build/generated/mame/layout \
    -I${MAME_BUILD}/src/osd/libretro \
    -I${MAME_BUILD}/src/osd/libretro/libretro-internal"
  local EMU_FLAGS="-O3 -DNDEBUG -std=c++20 -fPIC -D__LIBRETRO__ -DLIBRETRO_OS=unix"

  for src in machine.cpp video.cpp sound.cpp; do
    ${CXX} ${EMU_FLAGS} ${EMU_INCLUDES} \
      -c ${PKG_BUILD}/src/emu/${src} \
      -o ${PKG_BUILD}/libretro/tsugaru_${src%.cpp}.o
  done

  make -f libretro/Makefile.libretro \
    SRCROOT="${PKG_BUILD}" \
    OBJDIR="${PKG_BUILD}/libretro" \
    TARGET_OS=linux \
    CXX="${CXX}" \
    STRIP="${STRIP}" \
    ARCH="${ARCH}" \
    SHARED_FLAGS="-shared" \
    EXTRA_LIBS="" \
    LDFLAGS="${PKG_BUILD}/libretro/retro_globals_stub.o \
      ${PKG_BUILD}/libretro/netdev_common.o \
      ${PKG_BUILD}/libretro/tsugaru_machine.o \
      ${PKG_BUILD}/libretro/tsugaru_video.o \
      ${PKG_BUILD}/libretro/tsugaru_sound.o \
      -Wl,--start-group \
      ${LIBROOT}/mame_mame/liboptional.a \
      ${LIBROOT}/libemu.a \
      ${LIBROOT}/mame_mame/libformats.a \
      ${LIBROOT}/mame_mame/libdasm.a \
      ${LIBROOT}/mame_mame/libfujitsu.a \
      ${LIBROOT}/libutils.a \
      ${LIBROOT}/libsoftfloat.a \
      ${LIBROOT}/libsoftfloat3.a \
      ${LIBROOT}/libwdlfft.a \
      ${LIBROOT}/libymfm.a \
      ${LIBROOT}/libjpeg.a \
      ${LIBROOT}/lib7z.a \
      ${LIBROOT}/liblua.a \
      ${LIBROOT}/liblualibs.a \
      ${LIBROOT}/liblinenoise.a \
      ${LIBROOT}/libzstd.a \
      ${LIBROOT}/libnetlist.a \
      ${LIBROOT}/libasmjit.a \
      ${LIBROOT}/libutf8proc.a \
      ${LIBROOT}/mame_mame/libshared.a \
      ${LIBROOT}/mame_mame/libocore_retro.a \
      ${LIBROOT}/mame_mame/libosd_retro.a \
      -Wl,--end-group"
}

makeinstall_target() {
  mkdir -p ${INSTALL}/usr/lib/libretro
  cp -f ${PKG_BUILD}/libretro/fmtowns_libretro.so \
    ${INSTALL}/usr/lib/libretro/
}
