# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024-present EmuELEC Team (https://github.com/EmuELEC/EmuELEC)

PKG_NAME="openmsx"
PKG_VERSION="RELEASE_21_0"
PKG_REV="0"
PKG_ARCH="any"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/openMSX/openMSX"
PKG_URL="${PKG_SITE}/archive/refs/tags/${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain SDL2 SDL2_ttf libpng zlib tcl alsa-lib glew"
PKG_SHORTDESC="openMSX: The MSX emulator that aims for perfection"
PKG_TOOLCHAIN="manual"

_openmsx_patch() {
  local build="$1"

  # Patch 1: GCC 12 bug - static constexpr std::initializer_list rejected
  grep -rl 'static constexpr std::initializer_list' "${build}/src/" | \
    xargs sed -i 's/static constexpr std::initializer_list/static const std::initializer_list/g'

  # Patch 2: Remove GLScaler SUPERIMPOSE header prepend entirely.
  # gl4es preprocessor state leaks between glShaderSource calls: any
  # #ifndef...#endif in one compile corrupts the next shader compile.
  # The SUPERIMPOSE #if blocks are resolved in shader files at install
  # time, so no header is needed. Pass empty string instead.
  local f="${build}/src/video/scalers/GLScaler.cc"
  sed -i "s/tmpStrCat(\"#define SUPERIMPOSE \", char('0' + i), '\\\\n')/std::string()/g" "${f}"

  # Patch 3: Force OpenGL ES 2.0 context.
  # gl4es wraps GLES2 as desktop GL. OPENGL_2_1 compat profile fails
  # SDL_GL_CreateContext; OPENGL_ES_2_0 uses SDL_GL_CONTEXT_PROFILE_ES.
  sed -i 's/^#define OPENGL_VERSION OPENGL_2_1$/#define OPENGL_VERSION OPENGL_ES_2_0/' \
    "${build}/src/video/GLUtil.hh"
}

make_target() {
  local sysroot="${SYSROOT_PREFIX}"
  local real_cxx="${CXX%% *}"
  local cxx_dir="${PKG_BUILD}/.cxx"
  local wname
  wname="$(basename "${real_cxx}")"
  local cfg_dir="${PKG_BUILD}/derived/aarch64-linux-opt/config"

  # --- GL/glu.h stub -----------------------------------------------
  mkdir -p "${sysroot}/usr/include/GL"
  [ -f "${sysroot}/usr/include/GL/glu.h" ] || \
    printf '#ifndef __glu_h__\n#define __glu_h__\n/* GLU stub */\n#endif\n' \
      > "${sysroot}/usr/include/GL/glu.h"

  # --- CXX wrapper -------------------------------------------------
  mkdir -p "${cxx_dir}"
  cat > "${cxx_dir}/${wname}" << PYWRAP
#!/usr/bin/env python3
import sys, os
sysroot = "${sysroot}"
real    = "${real_cxx}"
args = []
for a in sys.argv[1:]:
    if   a.startswith('-I/usr/'): a = '-I' + sysroot + a[2:]
    elif a.startswith('-L/usr/'): a = '-L' + sysroot + a[2:]
    args.append(a)
os.execv(real, [real] + args)
PYWRAP
  chmod +x "${cxx_dir}/${wname}"

  # --- Replace probe.py with a no-op -------------------------------
  cat > "${PKG_BUILD}/build/probe.py" << 'NOOP'
import sys
sys.exit(0)
NOOP

  # --- Pre-generate probe outputs ----------------------------------
  mkdir -p "${cfg_dir}"

  cat > "${cfg_dir}/systemfuncs.hh" << SYSFUNCS
// Automatically generated.
#define HAVE_FTRUNCATE 1
#define HAVE_MMAP 1
SYSFUNCS

  cat > "${cfg_dir}/probed_defs.mk" << PROBEDEFS
# Automatically generated by build system.
# Non-empty value means found, empty means not found.
HAVE_ALSA_H:=true
HAVE_ALSA_LIB:=true
ALSA_CFLAGS:=
ALSA_LDFLAGS:=-lasound
HAVE_FREETYPE_H:=true
HAVE_FREETYPE_LIB:=true
FREETYPE_CFLAGS:=-I${sysroot}/usr/include/freetype2 -I${sysroot}/usr/include
FREETYPE_LDFLAGS:=-L${sysroot}/usr/lib -lfreetype
HAVE_GL_H:=true
HAVE_GL_LIB:=true
GL_CFLAGS:=
GL_LDFLAGS:=-lGL
HAVE_GLEW_H:=true
HAVE_GLEW_LIB:=true
GLEW_CFLAGS:=
GLEW_LDFLAGS:=-lGLEW -lGL
HAVE_OGG_H:=true
HAVE_OGG_LIB:=true
OGG_CFLAGS:=
OGG_LDFLAGS:=-logg
HAVE_PNG_H:=true
HAVE_PNG_LIB:=true
PNG_CFLAGS:=-I${sysroot}/usr/include/libpng16
PNG_LDFLAGS:=-lpng16
HAVE_SDL2_H:=true
HAVE_SDL2_LIB:=true
SDL2_CFLAGS:=-I${sysroot}/usr/include/SDL2 -D_REENTRANT
SDL2_LDFLAGS:=-lSDL2
HAVE_SDL2_TTF_H:=true
HAVE_SDL2_TTF_LIB:=true
SDL2_TTF_CFLAGS:=-I${sysroot}/usr/include/SDL2
SDL2_TTF_LDFLAGS:=-lSDL2_ttf
HAVE_TCL_H:=true
HAVE_TCL_LIB:=true
TCL_CFLAGS:=
TCL_LDFLAGS:=-ltcl8.6
HAVE_THEORA_H:=true
HAVE_THEORA_LIB:=true
THEORA_CFLAGS:=
THEORA_LDFLAGS:=-ltheoradec
HAVE_VORBIS_H:=true
HAVE_VORBIS_LIB:=true
VORBIS_CFLAGS:=
VORBIS_LDFLAGS:=-lvorbis
HAVE_ZLIB_H:=true
HAVE_ZLIB_LIB:=true
ZLIB_CFLAGS:=
ZLIB_LDFLAGS:=-lz
HAVE_FTRUNCATE:=true
HAVE_MMAP:=true
PROBEDEFS

  # --- Apply source patches ----------------------------------------
  _openmsx_patch "${PKG_BUILD}"

  # INSTALL_BASE=/usr burns /usr/share as the data path into the binary.
  make -C ${PKG_BUILD} \
    OPENMSX_TARGET_CPU=${TARGET_ARCH} \
    OPENMSX_TARGET_OS=linux \
    CXX="${cxx_dir}/${wname}" \
    CXXFLAGS="${TARGET_CFLAGS}" \
    INSTALL_BASE=/usr \
    V=1
}

makeinstall_target() {
  local sysroot="${SYSROOT_PREFIX}"
  local real_cxx="${CXX%% *}"
  local cxx_dir="${PKG_BUILD}/.cxx"
  local wname
  wname="$(basename "${real_cxx}")"

  make -C ${PKG_BUILD} \
    OPENMSX_TARGET_CPU=${TARGET_ARCH} \
    OPENMSX_TARGET_OS=linux \
    CXX="${cxx_dir}/${wname}" \
    INSTALL_BASE=/usr \
    DESTDIR=${INSTALL} \
    install

  # --- Shader preprocessing -------------------------------------
  # gl4es has a preprocessor state leak bug: #ifndef...#endif blocks
  # from one glShaderSource call corrupt state for subsequent calls,
  # causing "Unterminated #if" errors on unrelated shaders.
  # Fix: resolve all #if SUPERIMPOSE blocks at install time using the
  # SUPERIMPOSE=0 branch (superimpose = video overlay, not supported
  # on EmuELEC). This removes all preprocessor directives from the
  # installed shaders so gl4es never processes #if/#endif.
    python3 - "${INSTALL}/usr/share/shaders" << 'PYSHADER'
import sys, os, re as RE

sdir = sys.argv[1]
for fn in os.listdir(sdir):
    if not (fn.endswith('.frag') or fn.endswith('.vert')):
        continue
    fpath = os.path.join(sdir, fn)
    with open(fpath) as f:
        src = f.read()
    if '#if' not in src:
        continue
    def resolve(m):
        else_branch = m.group(2) if m.group(2) else ''
        return else_branch.strip() + '\n'
    src = RE.sub(
        r'#if SUPERIMPOSE[^\n]*\n(.*?)(?:#else[^\n]*\n(.*?))?#endif[^\n]*\n',
        resolve, src, flags=RE.DOTALL)
    src = RE.sub(r'#define SUPERIMPOSE [01]\n', '', src)
    with open(fpath, 'w') as f:
        f.write(src)
    print('Resolved SUPERIMPOSE in ' + fn)
PYSHADER

  # --- Launcher script ---------------------------------------------
  mkdir -p ${INSTALL}/usr/bin
  cp ${PKG_DIR}/scripts/startopenmsx.sh ${INSTALL}/usr/bin/startopenmsx.sh
  chmod +x ${INSTALL}/usr/bin/startopenmsx.sh

  # --- Config structure --------------------------------------------
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/gptk
  cp ${PKG_DIR}/config/openmsx.gptk \
    ${INSTALL}/usr/config/emuelec/configs/openmsx/gptk/openmsx.gptk

  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/share/machines
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/share/extensions
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/share/scripts
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/share/skins
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/persistent
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/savestates

  # --- libGLX runtime libs -----------------------------------------
  mkdir -p ${INSTALL}/usr/config/emuelec/configs/openmsx/libs
  for lib in libGLX.so.0 libGLdispatch.so.0; do
    if [ -f "${sysroot}/usr/lib/${lib}" ]; then
      cp "${sysroot}/usr/lib/${lib}" \
        "${INSTALL}/usr/config/emuelec/configs/openmsx/libs/${lib}"
    fi
  done
}